alias: Kotel - levny tarif
id: kotel_levny_tarif
description: Zapne kotel pri levne elektrine (HDO) - teplotu resi jina HA automatizace.
mode: single
trigger:
  - platform: time_pattern
    minutes: "/10"
condition:
  - condition: state
    entity_id: switch.shellypro3_ece334ed4534_switch_1
    state: "on"
  - condition: state
    entity_id: switch.shellypro3_ece334ed4534_switch_2
    state: "off"
action:
  - service: switch.turn_on
    target:
      entity_id: switch.shellypro3_ece334ed4534_switch_2
initial_state: true
