alias: Kotel - plna logika
id: kotel_plna_logika
description: >-
  Spousti vytapeni kotle ze solaru/baterie podle podminek (levny tarif, SOC, cas, teplota, rucni blokace).
mode: single
trigger:
  - platform: time_pattern
    minutes: "/10"
condition:
  - condition: state
    entity_id: switch.shellypro3_ece334ed4534_switch_1
    state: "on"
  - condition: state
    entity_id: switch.shellypro3_ece334ed4534_switch_2
    state: "off"
  - condition: numeric_state
    entity_id: sensor.alpha_ess_soc_battery
    above: 90
  - condition: sun
    after: sunrise
    after_offset: "01:00:00"
    before: sunset
    before_offset: "-02:00:00"
  - condition: template
    value_template: >-
      {{ states('sensor.shellyhtg3_e4b32332c5e8_temperature') | float(99)
         < states('input_number.fve_topi_az_do_xdegc') | float(0) }}
  - condition: state
    entity_id: input_boolean.rucne_vypnout_automatizaci_kotle
    state: "off"
action:
  - service: switch.turn_on
    target:
      entity_id: switch.shellypro3_ece334ed4534_switch_2
initial_state: true
